### ISSUE TITLE
Provide a way of knowing the display refresh rate

### ISSUE THREAD

**Issue by spite** [w3c/frame-timing#2]
Most devices are running at 60FPS, but that cannot be guaranteed: some devices might run at 120Hz, VR HMDs run at 75-90Hz, etc. In order to know if we're meeting the frame budget we need to know the target display rate too.

**Comment by igrigorik** [comment]
Note that the spec lives on wicg/frame-timing. Please take a look at https://github.com/WICG/frame-timing/issues/53. 

Closing, let's continue on wicg repo.
