### ISSUE TITLE
Make it available for all measured frames, not just observed slow frames

### ISSUE THREAD

**Issue by spite** [w3c/frame-timing#3]
My main issue with PerformanceObserver is that it only reports slow frames. A nice feature of a performance API would be to run some samples, and decide if the result is good enough: may be the app can then downscale some features to not run at 99% capacity.

**Comment by igrigorik** [comment]
That's where we started, but unfortunately we can't expose timing of every frame, see: https://github.com/WICG/frame-timing/pull/48
